### ISSUE TITLE
Configurator for macOS?

### ISSUE THREAD

**Issue by BabyFnord** [dekuNukem/duckyPad-Pro#4]
Hi @dekuNukem,

first time DPP user here. duckPad configurator 1.6.3 does not work with DPP. Is there no macOS (ARM if possible) equivalent to v2?

Tx, BF

**Comment by Bastiaantjuhh** [comment]
@BabyFnord DuckyPad Pro software (v2) is currently only avalible for Windows. Me also waiting for the MacOS version.

https://github.com/dekuNukem/duckyPad-Pro/releases/tag/2.0.0

**Comment by BabyFnord** [comment]
Thanks to pointers by @jbecker on Discord, I've assembled this reliably working method:
**Install/Update Configurator**
```
cd "$HOME"
git clone https://github.com/dekuNukem/duckyPad-Pro.git
mkdir duckyPad-Pro-VENV
python3 -m venv duckyPad-Pro-VENV
source duckyPad-Pro-VENV/bin/activate
pip install --upgrade pip
cd duckyPad-Pro/pc_software
python3 -m pip install -r requirements.txt
sudo python3 duckypad_config.py 
```

**Run Configurator**
```
cd "$HOME"
source duckyPad-Pro-VENV/bin/activate
cd duckyPad-Pro/pc_software
sudo python3 duckypad_config.py
```

Of course you could install/run it anywhere else than $HOME, if you want to. Case closed, at least for me :)
